version: '3.0'

services:
  db:
    build: ./db
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: carsAPI
  api:
    build: .
    container_name: cars-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - db
    depends_on:
      - db
    ports:
      - 2112:3000
    command: yarn start:dev
